export const VIPANEL_TEXTURES = [
  {
    id: 'CAR5AE',
    label: 'Travertine',
    url: '/textures/CAR5AE-Travertine-1500x2550x3MM.webp',
    category: 'clair',
    recommendedFor: ['gold', 'white', 'champagne'],
  },
  {
    id: 'CAR06B',
    label: 'Béton métallique',
    url: '/textures/CAR06B-Beton-metallique-1500x2550x3MM.webp',
    category: 'gris',
    recommendedFor: ['black', 'chrome', 'champagne'],
  },
  {
    id: 'CARP5B',
    label: 'Pierre castello clair',
    url: '/textures/CARP5B-Pierre-castello-clair-1500x2550x3MM.webp',
    category: 'clair',
    recommendedFor: ['gold', 'white', 'champagne'],
  },
  {
    id: 'CARP6B',
    label: 'Pierre castello foncé',
    url: '/textures/CARP6B-Pierre-castello-fonce-1500x2550x3MM.webp',
    category: 'dark',
    recommendedFor: ['black', 'bronze'],
  },
  {
    id: 'CNC3WP',
    label: 'Béton patiné',
    url: '/textures/CNC3WP-Beton-patine-1500x2550x3MM.webp',
    category: 'clair',
    recommendedFor: ['white', 'champagne', 'chrome'],
  },
  {
    id: 'CNC21P',
    label: 'Béton ciré',
    url: '/textures/CNC21P-Beton-cire-1500x2550x3MM.webp',
    category: 'clair',
    recommendedFor: ['white', 'chrome', 'champagne'],
  },
  {
    id: 'CNC24P',
    label: 'Béton gris',
    url: '/textures/CNC24P-Beton-gris-1500x2550x6MM.webp',
    category: 'gris',
    recommendedFor: ['black', 'chrome'],
  },
  {
    id: 'CNC25P',
    label: 'Béton anthracite',
    url: '/textures/CNC25P-Beton-anthracite-1500x2550x3MM.webp',
    category: 'dark',
    recommendedFor: ['black', 'bronze'],
  },
  {
    id: 'CNC29P',
    label: 'Béton noir',
    url: '/textures/CNC29P-Beton-noir-1500x2550x6MM.webp',
    category: 'dark',
    recommendedFor: ['black', 'bronze'],
  },
  {
    id: 'CR14RB',
    label: 'Quartzite deep blue',
    url: '/textures/CR14RB-Quartzite-deep-blue-1500x2550x3MM.webp',
    category: 'dark',
    recommendedFor: ['black', 'bronze', 'gold'],
  },

  {
    id: 'CR1X4B',
    label: 'Carrare doré',
    url: '/textures/CR1X4B-Carrare-dore-1500x2550x3MM.webp',
    category: 'clair',
    recommendedFor: ['gold', 'white', 'champagne'],
  },
  {
    id: 'CRI22B',
    label: 'Moonlight',
    url: '/textures/CRI22B-Moonlight-1500x2550x3MM.webp',
    category: 'clair',
    recommendedFor: ['gold', 'white', 'champagne'],
  },
  {
    id: 'CRI25P',
    label: 'Travertin gris',
    url: '/textures/CRI25P-Travertin-gris-1500x2550x3MM.webp',
    category: 'gris',
    recommendedFor: ['black', 'chrome', 'champagne'],
  },
  {
    id: 'CRI27P',
    label: 'Travertin blanc',
    url: '/textures/CRI27P-Travertin-blanc-1500x2550x3MM.webp',
    category: 'clair',
    recommendedFor: ['gold', 'white', 'champagne'],
  },
  {
    id: 'CRI28P',
    label: 'Classic travertin',
    url: '/textures/CRI28P-Classic-travertin-1500x2550x3MM.webp',
    category: 'clair',
    recommendedFor: ['gold', 'white', 'champagne'],
  },
  {
    id: 'FLR29V',
    label: 'Jardin secret',
    url: '/textures/FLR29V-Jardin-secret-1500x2550x3MM.webp',
    category: 'decor',
    recommendedFor: ['gold', 'white', 'champagne'],
  },
  {
    id: 'MAR3PB',
    label: 'Reflet nocturne',
    url: '/textures/MAR3PB-Reflet-nocturne-1500x2550x3MM.webp',
    category: 'dark',
    recommendedFor: ['black', 'bronze', 'gold'],
  },
  {
    id: 'MAR3PD',
    label: 'Reflet nocturne',
    url: '/textures/MAR3PD-Reflet-nocturne-1500x2550x3MM.webp',
    category: 'dark',
    recommendedFor: ['black', 'bronze', 'gold'],
  },
  {
    id: 'MAR3PR',
    label: 'Obsidienne',
    url: '/textures/MAR3PR-Obsidienne-grise-1500x2550x3MM.webp',
    category: 'dark',
    recommendedFor: ['black', 'bronze'],
  },
  {
    id: 'MAR4AP',
    label: 'Marbre évanescent',
    url: '/textures/MAR4AP-Marbre-evanescent-1500x2550x3MM.webp',
    category: 'clair',
    recommendedFor: ['gold', 'white', 'champagne'],
  },

  {
    id: 'MAR4BP',
    label: 'Clair minéral',
    url: '/textures/MAR4BP-Clair-mineral-1500x2550x3MM.webp',
    category: 'clair',
    recommendedFor: ['gold', 'white', 'champagne'],
  },
  {
    id: 'MAR4CB',
    label: 'Marbre arctique',
    url: '/textures/MAR4CB-Marbre-arctique-1500x2550x3MM.webp',
    category: 'clair',
    recommendedFor: ['gold', 'white', 'champagne'],
  },
  {
    id: 'MAR4YF',
    label: 'Chiara',
    url: '/textures/MAR4YF-Chiara-1500x2550x3MM.webp',
    category: 'clair',
    recommendedFor: ['gold', 'white', 'champagne'],
  },
  {
    id: 'ST03SP',
    label: 'Murano sable',
    url: '/textures/ST03SP-Murano-sable-1500x2550x3MM.webp',
    category: 'clair',
    recommendedFor: ['gold', 'white', 'champagne'],
  },
  {
    id: 'ST03UP',
    label: 'Murano graphite',
    url: '/textures/ST03UP-Murano-graphite-1500x2550x3MM.webp',
    category: 'dark',
    recommendedFor: ['black', 'bronze'],
  },
  {
    id: 'STO3YB',
    label: 'Pierre de printemps',
    url: '/textures/STO3YB-Pierre-de-printemps-1500x2550x3MM.webp',
    category: 'green',
    recommendedFor: ['gold', 'champagne', 'black'],
  },
  {
    id: 'STO3ZP',
    label: 'Petra natura',
    url: '/textures/STO3ZP-Petra-natura-1500x2550x3MM.webp',
    category: 'clair',
    recommendedFor: ['gold', 'white', 'champagne'],
  },
  {
    id: 'STO4OP',
    label: 'Stone gold',
    url: '/textures/STO4OP-Stone-gold-1500x2550x3MM.webp',
    category: 'clair',
    recommendedFor: ['gold', 'champagne'],
  },
  {
    id: 'STO33P',
    label: 'Pierre beige',
    url: '/textures/STO33P-Pierre-beige-1500x2550x3MM.webp',
    category: 'clair',
    recommendedFor: ['gold', 'white', 'champagne'],
  },
  {
    id: 'STO34P',
    label: 'Pierre grise',
    url: '/textures/STO34P-Pierre-grise-1500x2550x3MM.webp',
    category: 'gris',
    recommendedFor: ['black', 'chrome', 'champagne'],
  },

  {
    id: 'STO35S',
    label: 'Pierre ardoise grise',
    url: '/textures/STO35S-Pierre-ardoise-grise-1500x2550x3MM.webp',
    category: 'gris',
    recommendedFor: ['black', 'chrome'],
  },
  {
    id: 'STO38S',
    label: 'Pierre ardoise noire',
    url: '/textures/STO38S-Pierre-ardoise-noire-1500x2550x3MM.webp',
    category: 'dark',
    recommendedFor: ['black', 'bronze'],
  },
  {
    id: 'STO39P',
    label: 'Pierre noire',
    url: '/textures/STO39P-Pierre-noire-1500x2550x3MM.webp',
    category: 'dark',
    recommendedFor: ['black', 'bronze'],
  },
  {
    id: 'UNI28',
    label: 'Uni beige',
    url: '/textures/Uni-beige-N28-NCS-S0804-Y30R.webp',
    category: 'uni',
    recommendedFor: ['gold', 'white', 'champagne'],
  },
  {
    id: 'UNI52',
    label: 'Uni vert',
    url: '/textures/Uni-vert-N52-Pantone-5665C.webp',
    category: 'uni',
    recommendedFor: ['gold', 'white', 'champagne'],
  },
  {
    id: 'WLD4FV',
    label: 'Voile tropical 1',
    url: '/textures/WLD4FV-Voile-tropical-1-1250x2550x3MM.webp',
    category: 'decor',
    recommendedFor: ['gold', 'white', 'champagne'],
  },
  {
    id: 'WLD4GV',
    label: 'Voile tropical 2',
    url: '/textures/WLD4GV-Voile-tropical-2-1250x2550x3MM.webp',
    category: 'decor',
    recommendedFor: ['gold', 'white', 'champagne'],
  },
  {
    id: 'WLD4HV',
    label: 'Voile tropical 3',
    url: '/textures/WLD4HV-Voile-tropical-3-1250x2550x3MM.webp',
    category: 'decor',
    recommendedFor: ['gold', 'white', 'champagne'],
  },
  {
    id: 'WLD4NP',
    label: 'Industri al jungle 1',
    url: '/textures/WLD4NP-Industri-al-jungle-1-1250x2550x3MM.webp',
    category: 'decor',
    recommendedFor: ['black', 'bronze', 'champagne'],
  },
  {
    id: 'WLD4OP',
    label: 'Industri al jungle 2',
    url: '/textures/WLD4OP-Industri-al-jungle-2-1250x2550x3MM.webp',
    category: 'decor',
    recommendedFor: ['black', 'bronze', 'champagne'],
  },

  {
    id: 'WLD4PP',
    label: 'Industri al jungle 3',
    url: '/textures/WLD4PP-Industri-al-jungle-3-1250x2550x3MM.webp',
    category: 'decor',
    recommendedFor: ['black', 'bronze', 'champagne'],
  },
  {
    id: 'WLD4VV',
    label: 'Voile tropical 4',
    url: '/textures/WLD4VV-Voile-tropical-4-1250x2550x3MM.webp',
    category: 'decor',
    recommendedFor: ['gold', 'white', 'champagne'],
  },
  {
    id: 'WOD4DP',
    label: 'Timber waves',
    url: '/textures/WOD4DP-Timber-waves-1500x2550x3MM.webp',
    category: 'wood',
    recommendedFor: ['gold', 'white', 'champagne'],
  },
  {
    id: 'WOD4ZF',
    label: 'Cedro',
    url: '/textures/WOD4ZF-Cedro-1500x2550x3MM.webp',
    category: 'wood',
    recommendedFor: ['gold', 'white', 'champagne', 'black'],
  },
  {
    id: 'WOD14B',
    label: 'Peuplier',
    url: '/textures/WOD14B-Peuplier-1500x2550x3MM.webp',
    category: 'wood',
    recommendedFor: ['gold', 'white', 'champagne'],
  },
]

export const RECEVEUR_TEXTURES = [
  {
    id: 'rec-white',
    label: 'Blanc mat',
    url: '/textures/rec1.webp',
  },
  {
    id: 'rec-anthracite',
    label: 'Anthracite',
    url: '/textures/rec2.webp',
  },
  {
    id: 'rec-stone',
    label: 'Pierre',
    url: '/textures/rec3.jpg',
  },
]

export const SHOWER_TYPES = [
  {
    id: 'f',
    label: 'Walk-in', 
  },
  {
    id: 'c',
    label: 'Coulissante',
  },
  { 
    id: 'p',
    label: 'Pivotante',
  },
  {
    id: 'pp',
    label: 'Pivotante avex prolongation',
  }
]

export const FINITIONS = [
  {
    id: 'or-brosse',
    label: 'Profilé Or Brossé',
    color: '#caa649',
    metalness: 1,
    roughness: 0,
  },
  {
    id: 'canon-fusil',
    label: 'Profilé Canon Fusil',
    color: '#4B4A45',
    metalness: 0.8,
    roughness: 0.28,
  },
  {
    id: 'or-brillant',
    label: 'Profilé Or Brillant',
    color: '#D9B85F',
    metalness: 0.95,
    roughness: 0.12,
  },
  {
    id: 'argent-poli',
    label: 'Profilé Argent POLI',
    color: '#E8E8E4',
    metalness: 0.95,
    roughness: 0.08,
  },
  {
    id: 'or-rose',
    label: 'Profilé Or Rosé',
    color: '#C9A283',
    metalness: 0.85,
    roughness: 0.28,
  },
  {
    id: 'noir-mat',
    label: 'Profilé Noir Mat',
    color: '#1F1F1F',
    metalness: 0.4,
    roughness: 0.65,
  },
  {
    id: 'bronze',
    label: 'Profilé Bronze',
    color: '#7A5A43',
    metalness: 0.85,
    roughness: 0.32,
  },
]