export const VIPANEL_TEXTURES = [
    {
    id: 'CAR5AF',
    name: 'Travertine tiles',
    url: '/textures/vipanel/CAR5AF-Travertine-tiles-1500x2550x3MM.webp',
    metalness: 0.1,
    roughness: 0.8,
  },
  {
    id: 'CARO6B',
    name: 'Béton métallique',
    url: '/textures/vipanel/CARO6B-Beton-metallique-1500x2550x3MM.webp',
    metalness: 0.1,
    roughness: 0.8,
  },
  {
    id: 'CARP5B',
    name: 'Pierre Castello clair',
    url: '/textures/vipanel/CARP5B-Pierre-castello-clair-1500x2550x3MM.webp',
    metalness: 0.1,
    roughness: 0.8,
  },
  {
    id: 'CARP6B',
    name: 'Pierre Castello foncé',
    url: '/textures/vipanel/CARP6B-Pierre-castello-fonce-1500x2550x3MM.webp',
    metalness: 0.1,
    roughness: 0.8,
  },
  {
    id: 'CNC21P',
    name: 'Béton ciré',
    url: '/textures/vipanel/CNC21P-Beton-cire-1500x2550x3MM.webp',
    metalness: 0.1,
    roughness: 0.8,
  },
  {
    id: 'CNC24P',
    name: 'Béton gris',
    url: '/textures/vipanel/CNC24P-Beton-gris-1500x2050x6MM.webp',
    metalness: 0.1,
    roughness: 0.8,
  },
  {
    id: 'CNC25P',
    name: 'Béton anthracite',
    url: '/textures/vipanel/CNC25P-Beton-anthracite-1500x2550x3MM.webp',
    metalness: 0.1,
    roughness: 0.8,
  },
  {
    id: 'CNC29P',
    name: 'Béton noir',
    url: '/textures/vipanel/CNC29P-Beton-noir-1500x2550x6MM.webp',
    metalness: 0.1,
    roughness: 0.8,
  },
  {
    id: 'CNC3WP',
    name: 'Béton patiné',
    url: '/textures/vipanel/CNC3WP-Beton-patine-1500x2550x3MM.webp',
    metalness: 0.1,
    roughness: 0.8,
  },
  {
    id: 'CRI4RB',
    name: 'Quartzite deep blue',
    url: '/textures/vipanel/CRI4RB-Quartzite-deep-blue-1500x2550x3MM.webp',
    metalness: 0.1,
    roughness: 0.8,
  },
  {
    id: 'CRIX4B',
    name: 'Carrare doré',
    url: '/textures/vipanel/CRIX4B-Carrare-dore-1500x2550x3MM.webp',
    metalness: 0.1,
    roughness: 0.8,
  },
  {
    id: 'CRIZ2B',
    name: 'Moonlight',
    url: '/textures/vipanel/CRIZ2B-Moonlight-1500x2550x3MM.webp',
    metalness: 0.1,
    roughness: 0.8,
  },
  {
    id: 'CRIZ5P',
    name: 'Travertin gris',
    url: '/textures/vipanel/CRIZ5P-Travertin-gris-1500x2550x3MM.webp',
    metalness: 0.1,
    roughness: 0.8,
  },
  {
    id: 'CRIZ7P',
    name: 'Travertin blanc',
    url: '/textures/vipanel/CRIZ7P-Travertin-blanc-1500x2550x3MM.webp',
    metalness: 0.1,
    roughness: 0.8,
  },
  {
    id: 'CRIZ8P',
    name: 'Classic travertin',
    url: '/textures/vipanel/CRIZ8P-Classic-travertin-1500x2550x3MM.webp',
    metalness: 0.1,
    roughness: 0.8,
  },
  {
    id: 'FLRZ9V',
    name: 'Jardin secret',
    url: '/textures/vipanel/FLRZ9V-Jardin-secret-1500x2550x3MM.webp',
    metalness: 0.1,
    roughness: 0.8,
  },
  {
    id: 'MAR3PB',
    name: 'Reflet nocturne PB',
    url: '/textures/vipanel/MAR3PB-Reflet-nocturne-1500x2550x3MM.webp',
    metalness: 0.1,
    roughness: 0.8,
  },
  {
    id: 'MAR3PP',
    name: 'Reflet nocturne PP',
    url: '/textures/vipanel/MAR3PP-Reflet-nocturne-1500x2550x3MM.webp',
    metalness: 0.1,
    roughness: 0.8,
  },
  {
    id: 'MAR3RP',
    name: 'Obsidienne grise',
    url: '/textures/vipanel/MAR3RP-Obsidienne-grise-1500x2550x3MM.webp',
    metalness: 0.1,
    roughness: 0.8,
  },
  {
    id: 'MAR4AP',
    name: 'Marbre évanescent',
    url: '/textures/vipanel/MAR4AP-Marbre-evanescent-1500x2550x3MM.webp',
    metalness: 0.1,
    roughness: 0.8,
  },
  {
    id: 'MAR4BP',
    name: 'Clair minéral',
    url: '/textures/vipanel/MAR4BP-Clair-mineral-1500x2550x3MM.webp',
    metalness: 0.1,
    roughness: 0.8,
  },
  {
    id: 'MAR4CB',
    name: 'Marbre arctique',
    url: '/textures/vipanel/MAR4CB-Marbre-arctique-1500x2550x3MM.webp',
    metalness: 0.1,
    roughness: 0.8,
  },
  {
    id: 'MAR4YF',
    name: 'Chiara',
    url: '/textures/vipanel/MAR4YF-Chiara-1500x2550x3MM.webp',
    metalness: 0.1,
    roughness: 0.8,
  },
  {
    id: 'STO33P',
    name: 'Pierre beige',
    url: '/textures/vipanel/STO33P-Pierre-beige-1500x2550x3MM.webp',
    metalness: 0.1,
    roughness: 0.8,
  },
  {
    id: 'STO34P',
    name: 'Pierre grise',
    url: '/textures/vipanel/STO34P-Pierre-grise-1500x2550x3MM.webp',
    metalness: 0.1,
    roughness: 0.8,
  },
  {
    id: 'STO35S',
    name: 'Pierre ardoise grise',
    url: '/textures/vipanel/STO35S-Pierre-ardoise-grise-1500x2550x3MM.webp',
    metalness: 0.1,
    roughness: 0.8,
  },
  {
    id: 'STO38S',
    name: 'Pierre ardoise noire',
    url: '/textures/vipanel/STO38S-Pierre-ardoise-noire-1500x2550x3MM.webp',
    metalness: 0.1,
    roughness: 0.8,
  },
  {
    id: 'STO39P',
    name: 'Pierre noire',
    url: '/textures/vipanel/STO39P-Pierre-noire-1500x2550x3MM.webp',
    metalness: 0.1,
    roughness: 0.8,
  },
  {
    id: 'STO3SP',
    name: 'Murano sable',
    url: '/textures/vipanel/STO3SP-Murano-sable-1500x2550x3MM.webp',
    metalness: 0.1,
    roughness: 0.8,
  },
  {
    id: 'STO3UP',
    name: 'Murano graphite',
    url: '/textures/vipanel/STO3UP-Murano-graphite-1500x2550x3MM.webp',
    metalness: 0.1,
    roughness: 0.8,
  },
  {
    id: 'STO3YB',
    name: 'Pierre de printemps',
    url: '/textures/vipanel/STO3YB-Pierre-de-printemps-1500x2550x3MM.webp',
    metalness: 0.1,
    roughness: 0.8,
  },
  {
    id: 'STO3ZP',
    name: 'Petra natura',
    url: '/textures/vipanel/STO3ZP-Petra-natura-1500x2550x3MM.webp',
    metalness: 0.1,
    roughness: 0.8,
  },
  {
    id: 'STO4QP',
    name: 'Stone gold',
    url: '/textures/vipanel/STO4QP-Stone-gold-1500x2550x3MM.webp',
    metalness: 0.1,
    roughness: 0.8,
  },
  {
    id: 'UNI_BEIGE_28',
    name: 'Uni beige N°28',
    url: '/textures/vipanel/Uni-beige-N°28-NCS-S0804-Y30R.webp',
    metalness: 0.1,
    roughness: 0.8,
  },
  {
    id: 'UNI_VERT_52',
    name: 'Uni vert N°52',
    url: '/textures/vipanel/Uni-vert-N°52-Pantone-5665C.webp',
    metalness: 0.1,
    roughness: 0.8,
  },
  {
    id: 'WLD4FV',
    name: 'Voile tropical 1',
    url: '/textures/vipanel/WLD4FV-Voile-tropical-1-1250x2550x3MM.webp',
    metalness: 0.1,
    roughness: 0.8,
  },
  {
    id: 'WLD4GV',
    name: 'Voile tropical 2',
    url: '/textures/vipanel/WLD4GV-Voile-tropical-2-1250x2550x3MM.webp',
    metalness: 0.1,
    roughness: 0.8,
  },
  {
    id: 'WLD4HV',
    name: 'Voile tropical 3',
    url: '/textures/vipanel/WLD4HV-Voile-tropical-3-1250x2550x3MM.webp',
    metalness: 0.1,
    roughness: 0.8,
  },
  {
    id: 'WLD4NP',
    name: 'Industrial jungle 1',
    url: '/textures/vipanel/WLD4NP-Industrial-jungle-1-1250x2550x3MM.webp',
    metalness: 0.1,
    roughness: 0.8,
  },
  {
    id: 'WLD4OP',
    name: 'Industrial jungle 2',
    url: '/textures/vipanel/WLD4OP-Industrial-jungle-2-1250x2550x3MM.webp',
    metalness: 0.1,
    roughness: 0.8,
  },
  {
    id: 'WLD4PP',
    name: 'Industrial jungle 3',
    url: '/textures/vipanel/WLD4PP-Industrial-jungle-3-1250x2550x3MM.webp',
    metalness: 0.1,
    roughness: 0.8,
  },
  {
    id: 'WLD4VV',
    name: 'Voile tropical 4',
    url: '/textures/vipanel/WLD4VV-Voile-tropical-4-1250x2550x3MM.webp',
    metalness: 0.1,
    roughness: 0.8,
  },
  {
    id: 'WOD14B',
    name: 'Peuplier',
    url: '/textures/vipanel/WOD14B-Peuplier-1500x2550x3MM.webp',
    metalness: 0.1,
    roughness: 0.8,
  },
  {
    id: 'WOD4DP',
    name: 'Timber waves',
    url: '/textures/vipanel/WOD4DP-Timber-waves-1500x2550x3MM.webp',
    metalness: 0.1,
    roughness: 0.8,
  },
  {
    id: 'WOD4ZF',
    name: 'Cedro',
    url: '/textures/vipanel/WOD4ZF-Cedro-1500x2550x3MM.webp',
    metalness: 0.1,
    roughness: 0.8,
  },
]

export const RECEVEUR_TEXTURES = [
  {
    id: 'ardoxyde',
    label: 'Ardoxyde',
    url: '/textures/receveurs/Receveur_Ardoxyde.webp',
    category: 'dark',
    recommendedFor: ['noir-mat', 'bronze', 'canon-fusil'],
  },
  {
    id: 'greyge',
    label: 'Greyge',
    url: '/textures/receveurs/Receveur_Greyge.webp',
    category: 'clair',
    recommendedFor: ['or-brosse', 'or-rose', 'or-brillant', 'argent-poli'],
  },
  {
    id: 'gris-veine',
    label: 'Gris veiné',
    url: '/textures/receveurs/Receveur_Gris-veine.webp',
    category: 'gris',
    recommendedFor: ['noir-mat', 'canon-fusil', 'argent-poli'],
  },
  {
    id: 'soft-grey',
    label: 'Soft grey',
    url: '/textures/receveurs/Receveur_Soft-grey.webp',
    category: 'gris',
    recommendedFor: ['argent-poli', 'or-rose', 'canon-fusil'],
  },
  {
    id: 'soft-white',
    label: 'Soft white',
    url: '/textures/receveurs/Receveur_Soft-White.webp',
    category: 'clair',
    recommendedFor: ['or-brosse', 'or-brillant', 'argent-poli', 'or-rose'],
  },
]

export const SHOWER_TYPES = [
  {
    id: 'f',
    label: 'Walk-in', 
  },
  {
    id: 'c',
    label: 'Coulissante',
  },
  { 
    id: 'p',
    label: 'Pivotante',
  },
  {
    id: 'pp',
    label: 'Pivotante avex prolongation',
  }
]

export const FINITIONS = [
  {
    id: 'or-brosse',
    label: 'Profilé Or Brossé',
    color: '#caa649',
    metalness: 1,
    roughness: 0,
  },
  {
    id: 'canon-fusil',
    label: 'Profilé Canon Fusil',
    color: '#4B4A45',
    metalness: 0.8,
    roughness: 0.28,
  },
  {
    id: 'or-brillant',
    label: 'Profilé Or Brillant',
    color: '#D9B85F',
    metalness: 0.95,
    roughness: 0.12,
  },
  {
    id: 'argent-poli',
    label: 'Profilé Argent POLI',
    color: '#E8E8E4',
    metalness: 0.95,
    roughness: 0.08,
  },
  {
    id: 'or-rose',
    label: 'Profilé Or Rosé',
    color: '#C9A283',
    metalness: 0.85,
    roughness: 0.28,
  },
  {
    id: 'noir-mat',
    label: 'Profilé Noir Mat',
    color: '#1F1F1F',
    metalness: 0.4,
    roughness: 0.65,
  },
  {
    id: 'bronze',
    label: 'Profilé Bronze',
    color: '#7A5A43',
    metalness: 0.85,
    roughness: 0.32,
  },
]

export const PROFILES = [
  {
    id: 'or',
    label: 'Or',
    color: '#b89a45',
    metalness: 1,
    roughness: 0.18,
  },
  {
    id: 'blanc',
    label: 'Blanc',
    color: '#f2f2ef',
    metalness: 0.3,
    roughness: 0.35,
  },
  {
    id: 'argent',
    label: 'Argent',
    color: '#bfc0bd',
    metalness: 1,
    roughness: 0.12,
  },
  {
    id: 'noir',
    label: 'Noir',
    color: '#1f1f1f',
    metalness: 0.6,
    roughness: 0.45,
  },
]

